### ISSUE TITLE
APIResultsIterator total value not updated

### ISSUE THREAD

**Issue by Apipia** [tenable/pyTenable#148]
**Describe the bug**
Total value in APIResultsIterator seems to never change. Unless I am missing something, the total should, by its very own definition:  show "the total number of records that exist for the current request." It seems that this total value is in the parent class (APIResultsIterator) but is not implemented or maintained in the child class (ExportIterator).

**To Reproduce**
Initialize IO client.
Made an export for assets:
```
>>> from tenable.io import TenableIO
>>> client = TenableIO()
>>> assets = client.export.assets()
>>> assets.total
1
```

The only way for me to get a total count is to actually iterate:
```
>>> count = 0
... for asset in asset_req:
...     count +=1
```

**Expected behavior**
Was expecting a total count of all records to be returned.

**Screenshots**
N/A

**System Information (please complete the following information):**
 - OS: MacOS
 - Architecture: 64bit
 - Version: 10.14.6 
 - Memory: 16GB

**Additional context**
Looking at the code:
https://github.com/tenable/pyTenable/blob/2f7476c00333bcc53b2aa9f8eb9fc97e64b017fe/tenable/base.py#L34
It doesn't seem that this value is ever updated.
It appears that total is not at all used in the ExportsIterator within its next function as it is in its parent class. Would be nice to know what the total number of asset results is before any iteration starts.

**Comment by SteveMcGrath** [comment]
Correct, as the exports API is async, there is no way to know thew total until the export is completed.  It's also worth noting that the export iterator isnt making any status or chunk download calls until after you try to pull from the first page.  You can see this happening when you enable debug logging and walk through it.

It's worth noting that there is ExportIterator.count which is maintained, so there isn't a need to manage a counter externally.

https://github.com/tenable/pyTenable/blob/master/tenable/io/exports.py#L99

As for getting a simple total, this may be a better use case for the workbench APIs.  While the number of objects returned is limited to 5k (a UI constraint), it is returning unbounded totals.  Sadly the workbench methods return the list of objects instead of the full dictionary, so you'll need to make a raw method call like so:

```
total_assets = client.get('workbenches/assets').json()['total']
```
