### ISSUE TITLE
sourceType of 'individual' not allowed

### ISSUE THREAD

**Issue by rgeorgePscu** [tenable/pyTenable#151]
The comments read:

            source (str, optional):
                The data source location.  Allowed sources are ``cumulative``
                and ``patched``.  Defaults to ``cumulative``.

The code backs up this comment:

        if 'source' in kw:
            payload['sourceType'] = self._check('source', kw['source'], str,
                choices=['cumulative', 'patched'], case='lower')

Please add 'individual' as an option, the security center API does support this feature.

**Comment by SteveMcGrath** [comment]
Note that individual is implicitly set if you specify a scan ID.  secondly you shoudl really be using analysis.scan instead of analysis.vulns for this.

https://github.com/tenable/pyTenable/blob/master/tenable/sc/analysis.py#L332-L334
https://pytenable.readthedocs.io/en/stable/sc.html#tenable.sc.analysis.AnalysisAPI.scan
