### ISSUE TITLE
Issues filtering sc.analysis.vulns() method

### ISSUE THREAD

**Issue by smbenson** [tenable/pyTenable#235]
**Describe the bug**
I receive a `IndexError: tuple index out of range` error when passing a variable containing filter tuples. But when I pass those tuples as an argument directly, I do not receive an error.

**To Reproduce**

The following **does not work**:
```python3
cve_id = "CVE-2020-1472"
family = "10,20"
filter_tuple = ('cveID','=', cve_id),('familyID','=', family)
vulns = sc.analysis.vulns(filter_tuple)
```
This is the error returned:
```
Traceback (most recent call last):
  File "./p0_query_csv.py", line 179, in <module>
    vulns = sc.analysis.vulns(filter_tuple)
  File "/Library/Python/3.7/site-packages/tenable/sc/analysis.py", line 354, in vulns
    return self._analysis(*filters, **kw)
  File "/Library/Python/3.7/site-packages/tenable/sc/analysis.py", line 160, in _analysis
    kw = self._query_constructor(*filters, **kw)
  File "/Library/Python/3.7/site-packages/tenable/sc/base.py", line 214, in _query_constructor
    if f[1] != None and f[2] != None:
IndexError: tuple index out of range
```

However, the following **does work** and does not return the above error:
```
cve_id = "CVE-2020-1472"
family = "10,20"
vulns = sc.analysis.vulns(('cveID','=', cve_id),('familyID','=', family))
```

**Expected behavior**
I would expect to be able to pass a variable pointing to a tuple to the sc.analysis.vulns() method and get the same results as I would when defining the tuple within the method arguments.

**System Information (please complete the following information):**
 - OS: MacOS 10.15.6
 - Architecture: 64-bit
 - Version: 3.8.5
 - Memory: 32gb

**Comment by ChadKlunck** [comment]
There is a subtle (tricky?) difference between passing filters to Tenable.sc as direct arguments, versus passing the same filters as a collection of arguments stored in a variable.

**Working Code**
```python
vulns = sc.analysis.vulns(('cveID', '=', cve_id), ('familyID', '=', family))
```

is passing two arguments to the sc.analysis.vulns method:

1. A 3-tuple, containing the items 'cveID', '=', and cve_id
2. A 3-tuple, containing the items 'familyID', '=', and family

The vulns method is expecting that any tuples it receives as arguments will have exactly 3 items. Both of the passed arguments are 3-tuples, so pyTenable handles them properly.

**Non-Working Code**
```python
filter_tuple = ('cveID', '=', cve_id), ('familyID', '=', family)
vulns = sc.analysis.vulns(filter_tuple)
```

is passing a single argument, _filter_tuple_, which is a 2-tuple containing two 3-tuples:

1. ('cveID', '=', cve_id)
2. ('familyID', '=', family)

The IndexError is triggered because the code is trying to read the third index (f[2]) of the argument, which the code expects to be a 3-tuple. Since the non-working code is passing a 2-tuple instead of a 3-tuple, the code can only access f[0] and f[1], and throws an out of range error when trying to read f[2].

**Possible Fixes**
Here are a few ways to pass filters so the vulns method will understand them.

1. Variable as an n-tuple with unpacking

```python
filter_tuple = ('cveID', '=', cve_id), ('familyID', '=', family)
vulns = sc.analysis.vulns(*filter_tuple)
```

This option passes _filter_tuple_ as a single unnamed argument (in this case, a 2-tuple), and uses the unpacking operator (*) to break it into two separate arguments before processing.

2. Variable as a list with unpacking

```python
filter_list = [('cveID', '=', cve_id), ('familyID', '=', family)]
vulns = sc.analysis.vulns(*filter_list)
```

This option passes _filter_list_ as a single unnamed argument (in this case, a 2-item list), and uses the unpacking operator (*) to break it into two separate arguments before processing.

3. Keyword argument as a list (no unpacking required)

```python
filter_list = [('cveID', '=', cve_id), ('familyID', '=', family)]
vulns = sc.analysis.vulns(filters=filter_list)
```

This option passes _filter_list_ as a keyword argument. A couple of notes about keyword arguments for filters:

- pyTenable tests the value of _filters_ to ensure its type is `list`
- If you pass some filters as unnamed arguments, and also use the _filters_ named argument in the same method call, the unnamed arguments will be ignored in favor of the named ones

4. Multiple individual variables

```python
filter_one = ('cveID', '=', cve_id)
filter_two = ('familyID', '=', family)
vulns = sc.analysis.vulns(filter_one, filter_two)
```

I generally use option 3. Since lists are mutable, filters can be added at different points in the code (code defaults, entries in config files, run-time input by the user) simply by appending each new filter to the existing list. In your case, if your tuple isn't likely to change, the easiest answer is probably to add the unpacking operator as in option 1.

**Comment by SteveMcGrath** [comment]
You could perform this by informing the method that its a variable argument list:

```python
filter_tuples = (('cveID', '=', cve_id), ('familyID', '=', family))
vulns = sc.analysis.vulns(*filter_tuples)
```

This means that you could even do this in some other interesting ways if you had a dict in play, which may be common for thins like config files:

```python
items = {'cveID': 'abcd', 'familyID': 1}
vulns = sc.analysis.vulns(*[(i, '=', items[i]) for i in items])
```
