### ISSUE TITLE
policies.policy_import documentation string - wrong example syntax

### ISSUE THREAD

**Issue by mbrausen** [tenable/pyTenable#409]
https://github.com/tenable/pyTenable/blob/628fce951a884008cb7a28010214756236aede91/tenable/io/policies.py

Doc-strings for policy_import and policy_export had wrong examples:
tio.policies.import(policy)  -> should be tio.policies.policy_import(policy)
tio.policies.export(policy)  -> should be tio.policies.policy_export(policy)

**Comment by dheerajrp** [comment]
Hi @mbrausen 

We have made the changes and they are in [this PR](https://github.com/tenable/pyTenable/pull/427), since we were facing some problems while merging [your PR](https://github.com/tenable/pyTenable/pull/410) to pyTenable:master. So, please close your raised PR. We will merge this PR.

thanks

**Comment by mbrausen** [comment]
Closing PR as requested in [IN-463](https://github.com/tenable/pyTenable/tree/IN-463).
