### ISSUE TITLE
Document certificate based authentication for SC

### ISSUE THREAD

**Issue by nkeuning** [tenable/pyTenable#49]
**Is your feature request related to a problem? Please describe.**
SecurityCenter supports authenticating with only certificates, we need to support this for the Splunk app and federal customers

**Describe the solution you'd like**
The ability to authenticate using certificates rather than username/password. 

**Describe alternatives you've considered**
Writing our own wrappers to do this. 

**Additional context**
Heavily used in the fed sector and if implemented should let us swap out custom code for this library in the Tenable Add-On for Splunk. 💯

**Comment by SteveMcGrath** [comment]
cert-based auth can be accomplished either through passing the certificates via the certs parameter (if passwordless) or by using the requests-pkcs12 adaptor for passworded certs.

For passwordless certs:

    sc = TenableSC('localhost', certs=('certfile.pem', 'server.key'))

http://docs.python-requests.org/en/master/user/advanced/#client-side-certificates

For passworded certs:

    from requests_pkcs12 import Pkcs12Adapter
    adapter = Pkcs12Adapter(pkcs12_filename='certificate.p12', pkcs12_password='omgwtfbbq!')
    sc = TenableSC('localhost', adapter=adapter)

https://github.com/m-click/requests_pkcs12

I think the real issue is that this simply isn't documented as the TenableSC class doesn't have it's parameters documented yet.
