### ISSUE TITLE
Cannot import library in python 2.7 running on Mac OS X

### ISSUE THREAD

**Issue by cybersmithio** [tenable/pyTenable#55]
**Describe the bug**
On Mac OS X running python 2.7.10, when trying to import the library it cannot find the module named tenable.io

**To Reproduce**
```$ pip install pytenable
$ python
Python 2.7.10
>>> from tenable.io import TenableIO
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
ImportError: No module named tenable.io
```

**Expected behavior**
The module should be found and imported.  It works fine in Python 3 on the same Mac OS X system:
```$ python3
Python 3.7.1 
Type "help", "copyright", "credits" or "license" for more information.
>>> from tenable.io import TenableIO
>>>
```

**System Information (please complete the following information):**
 - OS: Mac OS X running 
 - Architecture 64 bit
 - Version python 2.7.10

**Comment by nkeuning** [comment]
- How did you install pyTenable?  pip install pytenable?
- Did you install into a virtualenv? 
- If not in a virtualenv did you install as root or with sudo?  
- What is the output of which pip?

My thought here is that somehow your env installed using pip for python3 rather than python2 whether that is a virtualenv or under a specific user causing a perms issue.  

Have you tried:
/usr/local/bin/pip2.7 install pytenable

**Comment by SteveMcGrath** [comment]
I’d have to agree with @nkeuning, this isn’t a pytenable issue, but is a python environment issue.  It appears that pip is installing to your python3 environment.  You may need to take a look at how pip is linked in.

I’d recommend that you actually isolate your own code from the system environment using virtualenv either way.  There are a few wrappers to handle this, most notably virtualenv-wrapper to make venvs painless.
