### ISSUE TITLE
Having Issues retrieving IP Summary data from Tenable Security Center

### ISSUE THREAD

**Issue by CyberTeam4321** [tenable/pyTenable#625]
**Describe the bug**
Unable to retrieve IP Summary Data from Tenable. I am unable to determine on which filter or function to use.

**To Reproduce**
from tenable.sc import TenableSC
sc = TenableSC()
sc.login(access_key=<access_key_value>, secret_key=<secret_key_value>)
payload = {'type': 'vuln', 'sourceType': 'patched'}
vulns = sc.analysis.vulns(*payload)
next(vulns)
**Expected behavior**
I should retrieve IP address which are scanned and the number of vulnerabilities it has for every IP address.

**Screenshots**
<img width="357" alt="IPSummary" src="https://user-images.githubusercontent.com/108571927/191018063-7d6b88b9-9430-4731-a6dc-93fc2dbf5d47.PNG">

**System Information (please complete the following information):**
 - OS: Windows
 - Architecture 64 BIT
 - Version Version pyTenable==1.4.6
 - Memory 4GB

**Additional context**

**Comment by ChadKlunck** [comment]
The sc.analysis.vulns() endpoint (and all of the other sc.analysis functions) accept two different parameters:
`*filters` - How T.sc results should be filtered. Accepts data in a **list**
`**kwargs` - Additional keyword arguments (how many results to return, how to sort, etc.). Accepts data in a **dictionary**

Your code is passing the dict 'payload', but because of the single asterisk, it's trying to process that variable as a list. Instead, use the double asterisk when passing keyword dictionaries. For some general info on how Python uses * and **, see [python.org : Unpacking Argument Lists](https://docs.python.org/3/tutorial/controlflow.html#unpacking-argument-lists).

As for which analysis tool to use, the list of options can be found in the docs at [sc.analysis.vulns](https://pytenable.readthedocs.io/en/stable/api/sc/analysis.html#tenable.sc.analysis.AnalysisAPI.vulns). The tool parameter for the IP summary is named "sumip". So something like the following should work:

```
payload = {'tool': 'sumip', 'sourceType': 'patched'}
vulns = sc.analysis.vulns(**payload)  # Note the two asterisks instead of one
while vulns:
    vuln = next(vulns)
    print(f"{vuln['ip']} has {vuln['total']} patched vulnerabilities.")
```
