### ISSUE TITLE
Exporting Multiple Scan Results

### ISSUE THREAD

**Issue by nessusnerd** [tenable/pyTenable#662]
Looking for guidance on how to export more than (1) scan result from Tenable.sc.
I am familiar with writing loops and have done it dozens of times in other scripts, but this method has proved challenging.

My script followed the syntax in the documentation:

with open('Compliance_Scan.zip', 'wb') as fobj:
     sc.scan_instances.export_scan(1150, fobj)

No problems running this whatsoever but I am looking for a way to export multiple scan reports.

When performing bulk operations, I typically read data in from large csv or json files.  But not sure how to do it here.  The 'id' parameter is looking for an integer and it won't accept a variable looped from a list of integers.

Any suggestions would be greatly appreciated!

**Comment by SteveMcGrath** [comment]
Is there any reason you aren't pulling the cumulative datastore instead?

**Comment by aseemsavio** [comment]
Could you include the looping logic too here?

**Comment by SteveMcGrath** [comment]
https://pytenable.readthedocs.io/en/stable/api/sc/analysis.html#tenable.sc.analysis.AnalysisAPI.vulns

**Comment by SteveMcGrath** [comment]
it returns an iterable, which is designed to run in a for loop or similar.  I'd encourage you to handle the data in that way instead of trying to download all of the data at once, as those datasets can be quite large and take a lot of memory to work through.

Analysis Iterator source: https://github.com/tenable/pyTenable/blob/master/tenable/sc/analysis.py#L82-L137
Base API Iterator: https://github.com/tenable/pyTenable/blob/master/tenable/base/v1.py

**Comment by nessusnerd** [comment]
I will give that a shot, thank you!
